// Code generated by genmocks.
// DO NOT EDIT!

package mocks

import "github.com/delabroj/weather"

type MockOpenWeatherClient struct {
	WeatherByCoordinatesFunc func(lat float64, lon float64) (weather.BasicWeather, error)
}

func NewMockOpenWeatherClient() *MockOpenWeatherClient {
	return &MockOpenWeatherClient{}
}

func (mockOpenWeatherClient *MockOpenWeatherClient) WeatherByCoordinates(lat float64, lon float64) (weather.BasicWeather, error) {
	return mockOpenWeatherClient.WeatherByCoordinatesFunc(lat, lon)
}
